spring:
  application:
    name: small-demo-jpa
    
  profiles:
    active: prd
    
---
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
---
server:
  port: 8801